version: "3.9"
services:
  web:
    build: .
    entrypoint: ./bin/entrypoint.sh
    command: ["rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:password@db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
