version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:password@db
      - RAILS_LOG_TO_STDOUT=enabled
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
